### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by gioamato**
• Update dependencies
• Fix a dead store variable
• Add support for secure cookies
• Add support for initial UTM parameters
• Add support for additional initial parameters 
• Add new documentation to README.md

### CODE REVIEW

**Comment by gioamato** [comment]
Just update CDN script src inside README.md when available.

**Comment by medius** [comment]
Thanks for the PR, @gioamato. This looks good. I'll review and merge asap.

**Comment by medius** [comment]
@gioamato I've updated the readme with the new CDN endpoint. Thanks a bunch for this PR.

**Comment by gioamato** [comment]
You are welcome.

**Pull request merged**
