### PR TITLE
Add 'decode_uris' option for field input values

### PR DESCRIPTION
**Pull request by rob**
This adds a `decode_uris` option to run field input values through `decodeURIComponent()` before being outputted, so URLs show up correctly (e.g., `https://` instead of `https%3A//`) when viewed in Mailchimp, etc.

(Based off of my previous PR branch - with updated gulp, etc.)

### CODE REVIEW

**Review by medius — CHANGES_REQUESTED** [review]
Would you mind creating a new version, say 1.0.5, for this? This will make sure that the old code is not overwritten and if someone wants to use the old version, they still can.

**Comment by medius** [comment]
@rob Perhaps the version number could be 1.1.0 for this. 

The rest of the changes look good to me. I'll wait for you to update this and then merge.

**Review by rob — COMMENTED** [review]
Should be all set.

**Comment by medius** [comment]
@rob Thanks for the PR. I'll upload the script to CDN and update README.

**Pull request merged**
